# Generated by Django 5.0.1 on 2024-01-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('image_frontside', models.ImageField(upload_to='transaction_images/')),
                ('image_backside', models.ImageField(upload_to='transaction_images/')),
                ('result', models.BooleanField()),
                ('error_code', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
